# 1. What is Self-Organization {#intro}

* Self-organised $\approx$ de-centralised phenomena
* 'Self-organizationg is a process in which pattern (sic) at the global level of a system emerges solely from numerous interactions among the lower-level components of the systemn. Moreover, the rules specifying interactions among the system's components are executed using only local information, without reference to the global pattern.'
	* Not an original thought :p, but the word 'global' made me realise how much of anthropogenic climate change was originally caused by a tragedy of the commons type situations. In the tragedy of the commons, each individual player harms public goods with more benefit for himself, while damaging the sustainability of the common resource -- without centralised control or command. In the absence of centralised regulation, this self-organised behaviour actually leads to unsustainable resource use! 
* 'The terms *chaos* and *dissipative stuctures have precise scientific meanings that may differ from popularized definitions....*' : the authors discuss complexity, without discussing either chaos or dissipative structures. I had never heard of the term 'dissipative structure' and this is my attempt at explaining it (Notes from [@prigogine1971biological]):
	* in physical systems, objects at 'equilibrium' are assumed to generally lack structure (eg. two liquids in a contained will diffuse until there is a uniform mixture). Lowering the temperature in general promotes the appearance of order/structure (eg. ice formation). However, lowering temperature need not be the only way to achieve order/structure. 
	* Order/structure can also result from systems that are far from equilibrium and are being *kept* away from it. The *Bénard flow* - where an oil layer heated from below forms hexagonal lattices. The lattices are formed through the action of convection, viscous and heat dissipation. These 'dissipative systems' thus form structures far from equilibrium because of the interaction of multiple processes. 
* The 'ocular dominance stripes' shown in Figure 1.2e caught my sustained attention. While I may have come across this pattern in my undergrad, I never noticed how the black and white strips actually code for cortical regions that prefer one eye or the other! The patterns indicate stable regions of the visual cortex that preferrably fire to inputs from either eye. Reading up at [@ocdomcol] pointed out that the combination of a few phenomena may result in stripes:
	* cortical neurons that are connected to each other and are locally excitatory but inhibitory over longer ranges 
	* Hebbian synapses (synapses that trigger more firings grow in strenght/connection)
	* similar/spatially patterned neural activity from the neurons coming into the cortex (from the eye)
* 